name: ClientPermissions
main: net.eq2online.permissions.plugin.ReplicatedPermissionsPlugin
version: ${project.version}
description: "\xa7bReplicates server permissions to control supported client side mods"
commands:
  clientperms:
    description: Client mod permission commands
    usage: "\xa7a/clientperms \xa7b<refresh|query|addmod|removemod|listmods|modversion>"
    aliases: clps
